config/routes.rb
Rails.application.routes.draw do
  root "stores#index"
  resources :stores do
    resources :items
  end
  Rails.application.routes.draw do  
    get '/stores', to: 'stores#index', as: 'all_the_stores'
    get '/store/:id', to: 'stores#show', as: 'the_one_store'
    delete '/store/:id', to: 'stores#destroy', as: 'destroy_the_store'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_store
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    @items = @store.items
  end

  def show
  end

  def new
    @item = @store.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create 
    @item = @store.items.new(item_params)

    if @item.save
      redirect_to [@store, @item]

    else
      render :new
    end
  end
  
  def update
    if @item.update(item_params)
      redirect_to [@store, @item]
      # same as redirect_to store_item_path(@store, @item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to store_items_path(@store)
  end

  private
    def set_store
      @store = Store.find(params[:store_id])
    end

    def set_item
      @item = item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :body)
    end


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit,:update,:destroy]
  def index
    @stores = Store.all
  end

  def show
   
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
 
    if @store.save
      redirect_to stores_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
  
    if @store.update(store_params)
      redirect_to store_path
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
  redirect_to stores_path 
  end

  private

   def store_params
     params.require(:store).permit(:shoe,:jecket,:hat,:kid,:food)
   end

   def set_store
    @store = Store.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@store, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @store.name %> - <%= @item.name %></h1>
<p><%= @item.body %></p>
<%= link_to 'Edit Item', edit_store_item_path([@store, @item]) %>
<%= link_to 'Delete Item', [@store, @item], method: :delete %>
<%= link_to 'Back To Items', store_items_path(@store) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Department</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_storestext.html.erb
<%= form_for @store do |f| %>
  <%= f.label :shoe %>
  <%= f.text_field :shoe%>
<br />
  <%= f.label :jecket %>
  <%= f.text_field :jecket %>
<br />
  <%= f.label :hat %>
  <%= f.text_field :hat %>
<br />
  <%= f.label :kid %>
  <%= f.text_field :kid %>
<br />
  <%= f.label :food %>
  <%= f.text_field :food %>
<br />
  <%= f.submit %>
<% end %>

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<%= render partial:"storestext"%>

app/views/stores/index.html.erb
<h1>Department Store</h1>

<% @stores.each do |store| %>
  <h2><%= store.shoe%></h2>
  <%= link_to 'Show Store', store_path(store) %>
   <%= link_to 'Edit Store', edit_store_path(store) %>
  <%= link_to 'Delete Store', store, method: :delete %>
<% end %>
<h1> Creat New Store </h1>
<p><%= link_to 'New Store', new_store_path %></p>

app/views/stores/new.html.erb
<h1>New Store</h1>
<%= render partial:"storestext" %>

app/views/stores/show.html.erb
<h1>Stores#show</h1>
<h1><%= @store.shoe %></h1>
<h4><%= @store.jecket %></h1>
<h4><%= @store.hat %></h4>
<h4><%= @store.kid %></h4>
<h4><%= @store.food %></h4>
<%= link_to 'Back', stores_path %>